#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
# 
# <lumingliang.github@gmail.com>

obj-y	:= fs2416.o
obj-y	+= lowlevel_init.o
